GET http://localhost:3000/api/peliculas

###

GET http://localhost:3000/api/peliculas?s=Dun

###

GET http://localhost:3000/api/peliculas/19

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "Django Sin Cadenas",
    "sinopsis": "Un dentista y cazarrecompensas alemán, el doctor King Schultz, consigue liberar a Django Freeman, un esclavo negro vendido a los hermanos Speck.",
    "anio": 2012
}

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "El tamalero2 Ya te atrape",
    "sinopsis": "Habla de que el señor ya encontro al tamalero, y le pidio dos de salsa roja pero el señor no tenía de esos",
    "anio": 2024
}

###

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "El tamalero3 Si habia de salsa roja",
    "sinopsis": "El tamalero si tenía de salsa roja solo que lo tenía escondido, entonces el señor se enojo y fue por churros",
    "anio": 2024
}

###

###

POST http://localhost:3000/api/peliculas
Content-Type: application/json

{
    "titulo": "El churrero",
    "sinopsis": "Proximamente solo en cines",
    "anio": 2024
}

###

PUT http://localhost:3000/api/peliculas/19
Content-Type: application/json

{
    "peliculaid": 19,
    "titulo": "Paw Patrol: La Súper Película",
    "sinopsis": "Un meteorito mágico aterriza en Adventure City y otorga superpoderes a los cachorros de PAW Patrol, convirtiéndolos en The Mighty Pups.",
    "anio": 2024,
    "poster": "https://m.media-amazon.com/images/M/MV5BMGI4NTNlODItMGJlZi00OTIwLTlkM2ItMWFkZjJhZDIzMDc3XkEyXkFqcGdeQXVyMTEyNzQ1MTk0._V1_SX300.jpg"
}

###

POST http://localhost:3000/api/peliculas/19/categoria
Content-Type: application/json

{
    "categoriaid": "2"
}

###

DELETE http://localhost:3000/api/peliculas/19/categoria
Content-Type: application/json

{
    "categoriaid": "1"
}

###

DELETE http://localhost:3000/api/peliculas/19